### ISSUE TITLE
Manage schedule shifts

### ISSUE THREAD

**Issue by r-mironov** [SquadcastHub/terraform-provider-squadcast#19]
It would be nice if provider could manage shifts. Can you add this feature?

**Comment by roshan8** [comment]
@r-mironov We are currently working on revamping schedules.
Terraform support will be added along with the feature release.

**Comment by r-mironov** [comment]
@roshan8 thank you

Can I track this release somewhere?

**Comment by roshan8** [comment]
It's in our immediate roadmap. We will update here once it gets released.

**Comment by dhaval512** [comment]
hi any update on this ?

**Comment by dhaval512** [comment]
any scheduled date for this released ? @roshan8

**Comment by ghost** [comment]
This is pretty key for adoption of the new scheduling system!

**Comment by roshan8** [comment]
This will be released next week. :)

**Comment by chriselion** [comment]
> This will be released next week. :)

Hi @roshan8 - that was two weeks ago. Any update?

**Comment by coreyti** [comment]
it appears that this implementation is near, in the form of a [`squadcast_schedule_v2`](https://github.com/SquadcastHub/terraform-provider-squadcast/blob/22c3f4ed3d64d5ac7d254b7174479a14f62817f9/docs/resources/schedule_v2.md) resource. I, too, am looking forward to this capability.

a suggestion: rather than introducing a new Terraform resource, update the existing `squadcast_schedule` resource to bring in these new capabilities. it seems that that only thing that would not be backward-compatible is the addition of the required `entity_owner` property. and, that would be caught easily. of course, users can also select a specific version of the provider, so being backward-compatible might not be critical at all. the only other potential challenge that comes to mind is that of state: there might be issues when migrating between the old an new implementations, if the resource is named the same. I, for one, would be fine with resolving those as needed.

in the end, using a new `_v2` resource is not actually all that big a deal. it just seems odd to me to bake the API version into the resource name, rather than the provider version.

**Comment by roshan8** [comment]
The provider version v1.4.3 has been released, enabling Terraform support for the new schedule!
This update allows for both schedule and rotation management. To provision new schedules, please utilize the schedule_resource_v2 and avoid importing legacy schedules into new resources, as the two utilize distinct APIs.

A few examples are also added for the creation of weekly & custom rotations :)
